### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by renatobellotti** [JuliaLang/IJulia.jl#1024]
I get the following error message when I try to start a Julia kernel in a fresh anaconda installation:

```
$ jupyter-lab
[I 2021-10-01 10:14:19.414 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-10-01 10:14:19.515 ServerApp] The module 'jupyterlab_late' could not be found. Are you sure the extension is installed?
[I 2021-10-01 10:14:19.515 ServerApp] nbclassic | extension was successfully linked.
[I 2021-10-01 10:14:19.532 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-10-01 10:14:19.532 LabApp] JupyterLab extension loaded from /home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyterlab
[I 2021-10-01 10:14:19.532 LabApp] JupyterLab application directory is /home/renato/.conda/envs/julia_env/share/jupyter/lab
[I 2021-10-01 10:14:19.534 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-10-01 10:14:19.535 ServerApp] Serving notebooks from local directory: /home/renato/Dokumente/ETH/PhD/TA/HS_21_22/icp-exercises/exercise_sheets_2021
[I 2021-10-01 10:14:19.535 ServerApp] Jupyter Server 1.11.0 is running at:
[I 2021-10-01 10:14:19.535 ServerApp] http://localhost:8888/lab?token=9e3516f0d2edc661c9d1e69eece59e63517f2a8ee0c65a10
[I 2021-10-01 10:14:19.535 ServerApp]  or http://127.0.0.1:8888/lab?token=9e3516f0d2edc661c9d1e69eece59e63517f2a8ee0c65a10
[I 2021-10-01 10:14:19.535 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-10-01 10:14:19.557 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/renato/.local/share/jupyter/runtime/jpserver-41855-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=9e3516f0d2edc661c9d1e69eece59e63517f2a8ee0c65a10
     or http://127.0.0.1:8888/lab?token=9e3516f0d2edc661c9d1e69eece59e63517f2a8ee0c65a10
[I 2021-10-01 10:14:23.421 LabApp] Build is up to date
[W 2021-10-01 10:14:31.929 ServerApp] Notebook 01/solution/solution_01.ipynb is not trusted
[I 2021-10-01 10:14:32.657 ServerApp] Kernel started: 82875722-5b4b-4176-b1f9-87d3892eba5a
[E 2021-10-01 10:14:37.349 ServerApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
        callback(*args, **kwargs)
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_client/session.py", line 1035, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'40f31faa80fd282fb7b370255bb2139f32de6ee32f8b2587409463157068b5a5a5f0535a438732b0e1b02eaa7cbaa2e0dd3b58d6d99d5cc812feb8e6070eb90f'
[E 2021-10-01 10:14:37.350 ServerApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
        self._handle_recv()
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
        callback(*args, **kwargs)
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_client/session.py", line 1035, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'40f31faa80fd282fb7b370255bb2139f32de6ee32f8b2587409463157068b5a5a5f0535a438732b0e1b02eaa7cbaa2e0dd3b58d6d99d5cc812feb8e6070eb90f'
Exception in callback BaseAsyncIOLoop._handle_events(24, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(24, 1)>
Traceback (most recent call last):
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
    msg = session.deserialize(fed_msg_list)
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/site-packages/jupyter_client/session.py", line 1035, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'40f31faa80fd282fb7b370255bb2139f32de6ee32f8b2587409463157068b5a5a5f0535a438732b0e1b02eaa7cbaa2e0dd3b58d6d99d5cc812feb8e6070eb90f'
Starting kernel event loops.
```

I think #421 is similar.

I mentioned my error already [here](https://github.com/JuliaLang/julia/issues/42448), but I realised it is probably two errors that are not related to each other.

I hope we can fix this problem because right now I cannot use Julia on my machine.

**Comment by gox6** [comment]
I have the same problem:

```
tmux attach -t julia

  File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv                                                 [12/110]
    self._run_callback(callback, msg)                                                                                                                                                
  File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback                                                        
    callback(*args, **kwargs)                                                                                                                                                        
  File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity                                
    msg = session.deserialize(fed_msg_list)                                                                                                                                          
  File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/jupyter_client/session.py", line 1054, in deserialize                                                          
    raise ValueError("Invalid Signature: %r" % signature)                                                                                                                            
ValueError: Invalid Signature: b'858e49b8bb22057779343659edb24e0af624de158774b247f007a954e5e65f1dd43876649a024d4cf04b77ad1d27fe387a0858353586d6ceb54ea5627e948a31'
Starting kernel event loops.
[W 2021-11-10 23:25:35.702 ServerApp] Timeout waiting for kernel_info reply from ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:40.217 ServerApp] Nudge: attempt 10 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:40.442 ServerApp] Nudge: attempt 10 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:40.578 ServerApp] Nudge: attempt 10 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:45.229 ServerApp] Nudge: attempt 20 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:45.455 ServerApp] Nudge: attempt 20 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:45.591 ServerApp] Nudge: attempt 20 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:50.241 ServerApp] Nudge: attempt 30 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:50.469 ServerApp] Nudge: attempt 30 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:50.605 ServerApp] Nudge: attempt 30 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:55.255 ServerApp] Nudge: attempt 40 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:55.483 ServerApp] Nudge: attempt 40 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:25:55.619 ServerApp] Nudge: attempt 40 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:00.267 ServerApp] Nudge: attempt 50 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:00.496 ServerApp] Nudge: attempt 50 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:00.632 ServerApp] Nudge: attempt 50 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:05.280 ServerApp] Nudge: attempt 60 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:05.509 ServerApp] Nudge: attempt 60 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:05.645 ServerApp] Nudge: attempt 60 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:10.292 ServerApp] Nudge: attempt 70 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:10.522 ServerApp] Nudge: attempt 70 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:10.658 ServerApp] Nudge: attempt 70 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
^[[A^[[A[W 2021-11-10 23:26:15.304 ServerApp] Nudge: attempt 80 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:15.534 ServerApp] Nudge: attempt 80 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:15.670 ServerApp] Nudge: attempt 80 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:20.318 ServerApp] Nudge: attempt 90 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:20.548 ServerApp] Nudge: attempt 90 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:20.684 ServerApp] Nudge: attempt 90 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:25.330 ServerApp] Nudge: attempt 100 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:25.560 ServerApp] Nudge: attempt 100 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:25.696 ServerApp] Nudge: attempt 100 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:30.343 ServerApp] Nudge: attempt 110 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:30.573 ServerApp] Nudge: attempt 110 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:30.709 ServerApp] Nudge: attempt 110 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:35.357 ServerApp] Nudge: attempt 120 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[I 2021-11-10 23:26:35.436 ServerApp] Saving file at /Untitled2.ipynb
[W 2021-11-10 23:26:35.587 ServerApp] Nudge: attempt 120 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[E 2021-11-10 23:26:35.706 ServerApp] Uncaught exception GET /api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels?session_id=0590adf5-eeac-48d9-b2c8-2e8e5c519a2b (83.31.72.182
)
    HTTPServerRequest(protocol='https', host='ec2-18-133-122-201.eu-west-2.compute.amazonaws.com:8846', method='GET', uri='/api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels
?session_id=0590adf5-eeac-48d9-b2c8-2e8e5c519a2b', version='HTTP/1.1', remote_ip='83.31.72.182')
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 2021-11-10 23:26:35.723 ServerApp] Nudge: attempt 120 on kernel ad081e23-1d4a-4798-a75c-0ccbfec67548
[W 2021-11-10 23:26:35.837 ServerApp] Replacing stale connection: ad081e23-1d4a-4798-a75c-0ccbfec67548:0590adf5-eeac-48d9-b2c8-2e8e5c519a2b
[E 2021-11-10 23:26:35.931 ServerApp] Uncaught exception GET /api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels?session_id=e870a84c-02ea-4bc2-a260-d4a3ca518229 (83.31.72.182
)
    HTTPServerRequest(protocol='https', host='ec2-18-133-122-201.eu-west-2.compute.amazonaws.com:8846', method='GET', uri='/api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels
?session_id=e870a84c-02ea-4bc2-a260-d4a3ca518229', version='HTTP/1.1', remote_ip='83.31.72.182')
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[E 2021-11-10 23:26:36.066 ServerApp] Uncaught exception GET /api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels?session_id=bf50bd28-a75b-4462-8580-70f7cdae700b (83.31.72.182
)
    HTTPServerRequest(protocol='https', host='ec2-18-133-122-201.eu-west-2.compute.amazonaws.com:8846', method='GET', uri='/api/kernels/ad081e23-1d4a-4798-a75c-0ccbfec67548/channels
?session_id=bf50bd28-a75b-4462-8580-70f7cdae700b', version='HTTP/1.1', remote_ip='83.31.72.182')
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/jl16/lib/python3.9/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 2021-11-10 23:27:05.930 ServerApp] WebSocket ping timeout after 90000 ms.
```

**Comment by shhgs** [comment]
I also met with this problem. I am using Julia 1.6.4. Python 3.9.7 and jupyter 6.4.6. 

The error message is 

```
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: [E 22:04:19.430 NotebookApp] Uncaught exception in ZMQStream callback                                                                                              
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     Traceback (most recent call last):
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         callback(*args, **kwargs)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 418, in record_activity
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         msg = session.deserialize(fed_msg_list)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/jupyter_client/session.py", line 1054, in deserialize
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         raise ValueError("Invalid Signature: %r" % signature)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     ValueError: Invalid Signature: b'0cab9fa7f11dd363c3127a4f8aa431bb6bbb981f04e55d3151425c6ddac3d62b7dbebbbe4c7d599dc540c5b8e2366ebdf1e0df34ef00a0cd22476caabf7e21e2'
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: [E 22:04:19.431 NotebookApp] Uncaught exception in zmqstream callback
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     Traceback (most recent call last):
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 448, in _handle_events
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         self._handle_recv()
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 477, in _handle_recv
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         self._run_callback(callback, msg)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         callback(*args, **kwargs)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 418, in record_activity
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         msg = session.deserialize(fed_msg_list)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:       File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/jupyter_client/session.py", line 1054, in deserialize
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:         raise ValueError("Invalid Signature: %r" % signature)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     ValueError: Invalid Signature: b'0cab9fa7f11dd363c3127a4f8aa431bb6bbb981f04e55d3151425c6ddac3d62b7dbebbbe4c7d599dc540c5b8e2366ebdf1e0df34ef00a0cd22476caabf7e21e2'
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(20, 1)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: handle: <Handle BaseAsyncIOLoop._handle_events(20, 1)>
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: Traceback (most recent call last):
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/asyncio/events.py", line 80, in _run
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     self._context.run(self._callback, *self._args)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     handler_func(fileobj, events)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 448, in _handle_events
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     self._handle_recv()
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 477, in _handle_recv
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     self._run_callback(callback, msg)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     callback(*args, **kwargs)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 418, in record_activity
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     msg = session.deserialize(fed_msg_list)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:   File "/opt/shhgs/conda/envs/py39/lib/python3.9/site-packages/jupyter_client/session.py", line 1054, in deserialize
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]:     raise ValueError("Invalid Signature: %r" % signature)
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: ValueError: Invalid Signature: b'0cab9fa7f11dd363c3127a4f8aa431bb6bbb981f04e55d3151425c6ddac3d62b7dbebbbe4c7d599dc540c5b8e2366ebdf1e0df34ef00a0cd22476caabf7e21e2'
Dec 16 22:04:19 jhuang-centos8 jupyter[936610]: Starting kernel event loops.
```

**Comment by gox6** [comment]
In my case the root cause for the above error was that I was installing Julia in Conda Env for Python.
Once I deactivated Conda, installed Julia it started to work and with nb_conda_kernels I got Julia Env in JupytetLab.

**Comment by JamesWrigley** [comment]
I could maybe possibly imagine this happening if somehow a different/unsupported build of mbedtls was installed by conda and did the wrong thing. But I'm not really sure 🤷 I'm going to close this because we switched to using the SHA stdlib instead of mbedtls recently, so hopefully that fixes whatever the issue is (but please comment if it happens again).
