### ISSUE TITLE
Running ipynb files through terminal

### ISSUE THREAD

**Issue by StatPal** [JuliaLang/IJulia.jl#1051]
I want to run .ipynb files through terminal so that the codes are executed and the outputs are saved. 
I have looked at #410  and tried commands like `jupyter nbconvert --to=html --template=basic --execute test.ipynb`, `jupyter nbconvert --execute test.ipynb` etc. They give the errors that ends with (detailed error is given at the end):
```
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```
I have also tried to transform the .ipynb files to .jl files through jupytext/NBInclude, but the output to terminal prints a lot whenever there is whole large array involved. 

Any help would be greatly appreciated. 
P.S. I am running everything through ssh.

Detailed error: 
```
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==6.5.0', 'console_scripts', 'jupyter-nbconvert')())
  File "/usr/bin/jupyter-nbconvert", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nbconvert/__init__.py", line 3, in <module>
    from . import filters, postprocessors, preprocessors, writers
  File "/usr/lib/python3.10/site-packages/nbconvert/filters/__init__.py", line 8, in <module>
    from .markdown import *
  File "/usr/lib/python3.10/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/usr/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 37, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

**Comment by nishtha981** [comment]
Looks like you're using a version of mistune being used by nbconvert may be outdated or incompatible with the current version of nbconvert.
Try updating the version of mistune by running the following code in your terminal
``` 
pip install --upgrade mistune 
 ```

Alternatively you can try reinstalling both mistune and nbconvert to ensure compatibility.

**Comment by JamesWrigley** [comment]
Closing this because the problem seems to be unrelated to IJulia.
