### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaLang/IJulia.jl#1063]
I downloaded the Julia 1.8.3 from the official website julialang.org/downloads for Windows X64 and installed the latest version of IJulia using `]add IJulia`. But I can't connect to kernel when I run `notebook()`:
![image](https://user-images.githubusercontent.com/52105833/209711396-13728aa1-3aba-4282-8d10-2aae4c7bf1d9.png)
When I click on the `Kernel error` button, it opens up a window with this content:
```
Failed to start the kernel
Unhandled error:
Traceback (most recent call last):
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1713, in _execute
    result = await result
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\notebook\services\sessions\handlers.py", line 74, in post
    model = yield maybe_future(
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\multikernelmanager.py", line 214, in _async_start_kernel
    starter = ensure_async(km.start_kernel(**kwargs))
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 90, in wrapper
    raise e
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 82, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 395, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\manager.py", line 311, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Shayan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```
```julia
julia> using IJulia

julia> notebook()
[ Info: running `'C:\Users\Shayan\.julia\conda\3\Scripts\jupyter.exe' notebook`
Process(setenv(`'C:\Users\Shayan\.julia\conda\3\Scripts\jupyter.exe' notebook`; dir="C:\\Users\\Shayan"), ProcessExited(0))

julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161 (2022-11-14 20:14 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_CONDAPKG_BACKEND = Null
  JULIA_PYTHONCALL_EXE = C:\Users\Shayan\AppData\Local\Programs\Python\Python310\python.exe
```

**Comment by stevengj** [comment]
Try running `]build IJulia` to make sure Jupyter knows the location of Julia (in case you moved/renamed it).

**Comment by shayandavoodii** [comment]
> Try running `]build IJulia` to make sure Jupyter knows the location of Julia (in case you moved/renamed it).

Thanks a lot! I did:
1. Open a Julia session
2. `]build IJulia`
3. `using IJulia`
4. `notebook()`
And now the kernel connects successfully.
Thanks a lot @stevengj <B

```julia
(@v1.8) pkg> build IJulia
    Building Conda ─→ `C:\Users\Shayan\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\6e47d11ea2776bc5627421d59cdcc1296c058071\build.log`
    Building IJulia → `C:\Users\Shayan\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\59e19713542dd9dd02f31d59edbada69530d6a14\build.log`

julia> using IJulia

julia> notebook()
[ Info: running `'C:\Users\Shayan\.julia\conda\3\Scripts\jupyter.exe' notebook`
```

**Comment by shayandavoodii** [comment]
BTW, is it possible to change the tab size and the indent size in IJulia's notebook?

**Comment by stevengj** [comment]
See https://jupyter-notebook.readthedocs.io/en/stable/frontend_config.html
