### ISSUE TITLE
Cannot run -- OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dcarrera** [JuliaLang/IJulia.jl#117]
I recently installed Julia from sources, as well as IPython and IJulia. I got IPython working, but when I try to run IJulia I get the following errors:

```
% ipython notebook --profile julia
2013-11-24 13:25:09.720 [NotebookApp] Using existing profile dir: u'/home/daniel/.config/ipython/profile_julia'
2013-11-24 13:25:09.726 [NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
2013-11-24 13:25:09.738 [NotebookApp] Serving notebooks from local directory: /home/daniel/Misc/src/ipython
2013-11-24 13:25:09.738 [NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8998/
2013-11-24 13:25:09.738 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
ERROR:root:Uncaught exception POST /kernels?notebook=dff4c80c-84cc-457c-b331-52b5d2fb40c3 (127.0.0.1)
HTTPRequest(protocol='http', host='127.0.0.1:8998', method='POST', uri='/kernels?notebook=dff4c80c-84cc-457c-b331-52b5d2fb40c3', version='HTTP/1.1', remote_ip='127.0.0.1', body='', headers={'Origin': 'http://127.0.0.1:8998', 'Content-Length': '0', 'Accept-Language': 'en-GB,en;q=0.8,en-US;q=0.6,de-DE;q=0.4,de;q=0.2,es-419;q=0.2,es;q=0.2', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': '127.0.0.1:8998', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/30.0.1599.114 Chrome/30.0.1599.114 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8998/dff4c80c-84cc-457c-b331-52b5d2fb40c3'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 954, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1667, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/kernels/handlers.py", line 46, in post
    kernel_id = km.start_kernel(notebook_id, cwd=nbm.notebook_dir)
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/services/kernels/kernelmanager.py", line 86, in start_kernel
    kernel_id = super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/multikernelmanager.py", line 115, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/manager.py", line 205, in start_kernel
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/manager.py", line 161, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/launcher.py", line 251, in launch_kernel
    stdin=_stdin, stdout=_stdout, stderr=_stderr, cwd=cwd, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR:root:500 POST /kernels?notebook=dff4c80c-84cc-457c-b331-52b5d2fb40c3 (127.0.0.1) 12.80ms
```

When I run "ipython qtconsole --profile julia" I get similar errors. No idea what's missing.

**Comment by stevengj** [comment]
No longer relevant with Jupyter
