### ISSUE TITLE
Failed to start the kernel on IPython 3.0.0

### ISSUE THREAD

**Issue by awellis** [JuliaLang/IJulia.jl#253]
When starting IJulia with IPython 3.0.0-dev, the kernel fails to start. Both IPython and R are fine. Julia previously worked with the current dev version of Python.

``` Python
[E 00:31:23.806 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/andrew/src/ipython/IPython/html/base/handlers.py", line 360, in wrapper
        result = method(self, *args, **kwargs)
      File "/Users/andrew/src/ipython/IPython/html/services/sessions/handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/Users/andrew/src/ipython/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "/Users/andrew/src/ipython/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "/Users/andrew/src/ipython/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/andrew/src/ipython/IPython/kernel/manager.py", line 240, in start_kernel
        **kw)
      File "/Users/andrew/src/ipython/IPython/kernel/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/andrew/src/ipython/IPython/kernel/launcher.py", line 213, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/andrew/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/Users/andrew/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[E 00:31:23.809 NotebookApp] {
      "Origin": "http://localhost:8888",
      "Content-Length": "79",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5",
      "Dnt": "1",
      "Host": "localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/generate_data.ipynb",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
    }
[E 00:31:23.811 NotebookApp] 500 POST /api/sessions (127.0.0.1) 22.29ms referer=http://localhost:8888/notebooks/generate_data.ipynb
^C[I 00:31:37.202 NotebookApp] interrupted
Serving notebooks from local directory: /Users/andrew/julia
0 active kernels
The IPython Notebook is running at: http://localhost:8888/
Shutdown this notebook server (y/[n])? ^C[C 00:31:37.481 NotebookApp] received signal 2, stopping
[I 00:31:37.482 NotebookApp] Shutting down kernels
```

**Comment by QGB** [comment]
in babun ,I got same problem
