### ISSUE TITLE
Installation fails on Ubuntu 16.04 for both Julia 0.4 and Julia 0.5

### ISSUE THREAD

**Issue by luav** [JuliaLang/IJulia.jl#473]
IJulia installation fails on Ubuntu 16.04 for both Julia 0.4 and Julia 0.5.

$ julia -v
julia version 0.5.0 (official Ubuntu package julia 0.5.0-xenial3)

```
julia> Pkg.build("IJulia")
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.1.0: jupyter
Writing IJulia kernelspec to /home/lav/.julia/v0.5/IJulia/deps/julia-0.5/kernel.json ...
Installing julia kernelspec julia-0.5
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 44, in <module>
    _libsodium = ctypes.CDLL(bundled_sodium[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: undefined symbol: _Py_InitPyPyModule
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 44, in <module>
    _libsodium = ctypes.CDLL(bundled_sodium[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: undefined symbol: _Py_InitPyPyModule
```
Removement and reinstall of pyzmq and/or libzmq does not solve the issue. Official Ubuntu 16.04 packages are used:
```
$ sudo ldconfig -p | grep "zmq"
	libzmq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.5
	libzmq.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.3
	libzmq.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.1
	libzmq.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so

$ dpkg -l "libzmq*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libzmq-dev:amd 2.2.0+dfsg-7 amd64        lightweight messaging kernel (dev
ii  libzmq1:amd64  2.2.0+dfsg-7 amd64        lightweight messaging kernel (sha
ii  libzmq3:amd64  4.0.4+dfsg-2 amd64        lightweight messaging kernel (sha
ii  libzmq5:amd64  4.1.4-7      amd64        lightweight messaging kernel (sha

```

NOTE:
* This issue differs from #437
* IJulia worked fine on Ubuntu 14.04 until the OS upgrade to 16.04

**Comment by stevengj** [comment]
You have misinstalled something — note the error message about missing `/usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so`.

It sounds like you are *not* using the official Ubuntu packages, because it is running `/usr/local/bin/jupyter-kernelspec` (and not `/usr/bin/jupyter`).  So, this is not an Ubuntu problem, it is a problem with however you've installed Jupyter.   Probably you have a custom installation that got broken when you upgraded Ubuntu.

**Comment by luav** [comment]
Thank you @stevengj! The jupyter was installed via pip, but somehow it was run under pypy (another official Ubuntu package: apt-get install pypy).
I removed pypy, reinstalled jupyter and IJulia under python. The installation was successful, but the *Julia kernel failed on notebook start*:
```
[I 19:21:34.773 NotebookApp] Creating new notebook in 
[I 19:21:35.837 NotebookApp] Kernel started: fa3095d7-93e3-41dc-b08e-ee814f0cfcf0
INFO: Precompiling module IJulia.
ERROR: LoadError: InitError: ZMQ version 2.2.0 < 3 is not supported
 in __init__() at /home/lav/.julia/v0.5/ZMQ/src/ZMQ.jl:595
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in require(::Symbol) at ./loading.jl:371
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
during initialization of module ZMQ
while loading /home/lav/.julia/v0.5/IJulia/src/IJulia.jl, in expression starting on line 38
ERROR: LoadError: Failed to precompile IJulia to /home/lav/.julia/lib/v0.5/IJulia.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/lav/.julia/v0.5/IJulia/src/kernel.jl, in expression starting on line 1
```
According to the error log libzmq was outdated:
```
$ dpkg -l "libzmq*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libzmq-dev:amd 2.2.0+dfsg-7 amd64        lightweight messaging kernel (dev
ii  libzmq1:amd64  2.2.0+dfsg-7 amd64        lightweight messaging kernel (sha
ii  libzmq3:amd64  4.0.4+dfsg-2 amd64        lightweight messaging kernel (sha
ii  libzmq5:amd64  4.1.4-7      amd64        lightweight messaging kernel (sha
```

Then I installed `libzmq3-dev` instead of default `libzmq-dev`: `$ sudo apt-get install libzmq3-dev`
Then reinstalled pyzmq: `$ sudo pip install pyzmq` under the python:
```
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```
Then reinstalled IJulia: `julia> Pkg.add("IJulia")` and finally it runs successfully!
Thanks a lot!

**Comment by stevengj** [comment]
Great!
