### ISSUE TITLE
Error Building IJulia: "ImportError: cannot import name constants"

### ISSUE THREAD

**Issue by geogunow** [JuliaLang/IJulia.jl#481]
I am trying to install IJulia properly and am having difficulty getting it working. As such, I completely nuked my .julia directory installation and reinstalled doing:

```
ENV["PYTHON"]=""
ENV["JUPYTER"]=""
Pkg.init()
Pkg.checkout("Conda")
Pkg.build("Conda")
Pkg.checkout("PyCall")
Pkg.build("PyCall")
Pkg.checkout("IJulia")
Pkg.build("IJulia")
```

I get the following error output:

```
julia> Pkg.build("IJulia")
INFO: Building Conda
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/geogunow/.julia/v0.5/Conda/deps/usr:
#
jupyter                   1.0.0                    py27_3  
INFO: Found Jupyter version 4.2.0: /home/geogunow/.julia/v0.5/Conda/deps/usr/bin/jupyter
Writing IJulia kernelspec to /home/geogunow/.julia/v0.5/IJulia/deps/julia-0.5/kernel.json ...
Installing julia kernelspec julia-0.5
Traceback (most recent call last):
  File "/home/geogunow/.julia/v0.5/Conda/deps/usr/bin/jupyter-kernelspec", line 2, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/geogunow/.local/lib/python2.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/geogunow/.local/lib/python2.7/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
Traceback (most recent call last):
  File "/home/geogunow/.julia/v0.5/Conda/deps/usr/bin/jupyter-kernelspec", line 2, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/geogunow/.local/lib/python2.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/geogunow/.local/lib/python2.7/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
```

**Comment by stevengj** [comment]
Normally you shouldn't checkout `master` versions of packages unless you know what you are doing.  And you don't need to manually install dependencies.  It should have been enough to do
```jl
ENV["PYTHON"]=""
ENV["JUPYTER"]=""
Pkg.add("IJulia")
```

The problem seems to be stemming from having multiple conficting versions of ZMQ installed on your system (http://stackoverflow.com/questions/32643383/importerror-cannot-import-name-constants).

In particular, it looks like you have another version of the libraries installed in `/home/geogunow/.local`, and I'm guessing that you have manually set up a `PYTHONPATH` or similar environment variable that is telling Python to look there.   Look at your environment variables (via `ENV` in Julia or `env` in the shell) and unset any that have to do with Python.

**Comment by stevengj** [comment]
IJulia no longer uses python to install.
