### ISSUE TITLE
IJulia won't start in Julia 0.6

### ISSUE THREAD

**Issue by NickMcNutt** [JuliaLang/IJulia.jl#504]
I upgraded Julia to master a few days ago, and it seems to no longer be compatible with IJulia.  Here is the Jupyter log.

```
[W 12:35:35.833 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 12:35:35.845 NotebookApp] Serving notebooks from local directory: /Users/Nick/projects/groupsync
[I 12:35:35.845 NotebookApp] 0 active kernels
[I 12:35:35.845 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 12:35:35.845 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:35:40.122 NotebookApp] 302 GET / (::1) 1.05ms
[I 12:35:44.131 NotebookApp] Creating new notebook in
[I 12:35:44.915 NotebookApp] Kernel started: eacff704-2f1d-4893-97bb-e5781d9d6b39
[W 12:35:44.933 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170123123535 (::1) 13.63ms referer=http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=julia-0.6
Starting kernel event loops.
[E 12:35:50.466 NotebookApp] Bad kernel_info reply
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 164, in _handle_kernel_info_reply
        msg = self.session.deserialize(msg)
      File "/usr/local/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: '476cdf035239ecaa79ae8fce18ab2a4917d7ca8fcec5b6bddec435102c0f4a9f'
[E 12:35:50.506 NotebookApp] Uncaught exception GET /api/kernels/eacff704-2f1d-4893-97bb-e5781d9d6b39/channels?session_id=1B0A0CDD128C4E58BD36B99AE0E85A60 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/eacff704-2f1d-4893-97bb-e5781d9d6b39/channels?session_id=1B0A0CDD128C4E58BD36B99AE0E85A60', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': 'csTinX3yKC579TFjV4hB7w==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'Connection': 'Upgrade', 'Cookie': '_xsrf=2|c278b476|652c3bc99f03b17447897ddc3ac3a32e|1484791836; _ga=GA1.1.1314284765.1484858166', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/usr/local/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: '5bd3e4b881ec529468d5b5699184a412572fc3395e3f64b4e50666106ecf275d'
[E 12:37:40.331 NotebookApp] Uncaught exception GET /api/kernels/eacff704-2f1d-4893-97bb-e5781d9d6b39/channels?session_id=1B0A0CDD128C4E58BD36B99AE0E85A60 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/eacff704-2f1d-4893-97bb-e5781d9d6b39/channels?session_id=1B0A0CDD128C4E58BD36B99AE0E85A60', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': '+i6qjAyvhivqEQjOkiRp3w==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'Connection': 'Upgrade', 'Cookie': '_xsrf=2|c278b476|652c3bc99f03b17447897ddc3ac3a32e|1484791836; _ga=GA1.1.1314284765.1484858166', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/usr/local/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'e2cfadcbcc0c8699478a505c7b27e19f70860003b0a2616a5ce7fd18abc08a6c'
```

**Comment by stevengj** [comment]
@malmaud, since the HMAC signature seems to be at issue, could this have been caused by #447?

**Comment by NickMcNutt** [comment]
So with a little more investigation, I notice that this error does not come up if I change kernel.json to start Julia with `--depwarn=no` (because Array(Float64, 1) is no longer valid, a ton of depwarns appear).  So it seems this is a problem with displaying a whole bunch of warning messages at once.

**Comment by stevengj** [comment]
Weird, I wonder if it is a race condition of some kind?

In any case, the deprecation warnings should disappear as we get closer to a 0.6 release and packages get updated.

**Comment by malmaud** [comment]
I checked; the error on julia master is the same even before the MbedTLS PR.

**Comment by malmaud** [comment]
I'm a little puzzled - even after checking out the master of ZMQ.jl, thereby eliminating the dep warnings, the error persists. Something with Julia master may be affecting IJulia and/or ZMQ in a subtle way.

**Comment by stevengj** [comment]
IJulia has been working on 0.6 for a while now, so presumably this can be closed.
