### ISSUE TITLE
`installkernel` with multiple options gives error in v0.6.2

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/IJulia.jl#612]
I am running:
```
IJulia.installkernel("Julia -O3 --depwarn=no", "-O3", "--depwarn-no")
```
and getting:
```
Traceback (most recent call last):
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/bin/jupyter-kernelspec", line 6, in <module>
    sys.exit(jupyter_client.kernelspecapp.KernelSpecApp.launch_instance())
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 274, in install_kernel_spec
    raise ValueError("Invalid kernel name %r.  %s" % (kernel_name, _kernel_name_description))
ValueError: Invalid kernel name u'julia--o3---depwarn=no-0.6'.  Kernel names can only contain ASCII letters and numbers and these separators: - . _ (hyphen, period, and underscore).
Traceback (most recent call last):
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/bin/jupyter-kernelspec", line 6, in <module>
    sys.exit(jupyter_client.kernelspecapp.KernelSpecApp.launch_instance())
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/home/mohd/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 274, in install_kernel_spec
    raise ValueError("Invalid kernel name %r.  %s" % (kernel_name, _kernel_name_description))
ValueError: Invalid kernel name u'julia--o3---depwarn=no-0.6'.  Kernel names can only contain ASCII letters and numbers and these separators: - . _ (hyphen, period, and underscore).
ERROR: failed process: Process(`/home/mohd/.julia/v0.6/Conda/deps/usr/bin/jupyter-kernelspec install --replace --user /tmp/julia--o3---depwarn=no-0.6`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] #installkernel#4(::String, ::Function, ::String, ::String, ::Vararg{String,N} where N) at /home/mohd/.julia/v0.6/IJulia/src/../deps/kspec.jl:79
 [4] installkernel(::String, ::String, ::Vararg{String,N} where N) at /home/mohd/.julia/v0.6/IJulia/src/../deps/kspec.jl:36
```

**Comment by mohamed82008** [comment]
Actually it was the name of the kernel that was invalid. Should I open another issue?

**Comment by stevengj** [comment]
Yes.
