### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by fififionaz** [JuliaLang/IJulia.jl#624]
Traceback (most recent call last):
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/manager.py", line 258, in start_kernel
    **kw)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/fifizhang/.julia/v0.6/Conda/deps/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by stevengj** [comment]
`No such file or directory` probably means that you need to run `Pkg.build("IJulia")` in Julia to tell Jupyter where Julia is.  (e.g. if you upgraded Julia and moved it to a new directory).
