### ISSUE TITLE
Continuously-updating display (ProgressMeter)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/IJulia.jl#65]
The ProgressMeter package generates and updates a "status bar" as progress is made through a long-running computation. It uses escaping tricks to rewrite the last line of console output.

When running inside IJulia, I get messages like these in the bash console from which I launched ipython notebook:

```
JSONDecodeError: Invalid \escape: line 1 column 37 (char 37)
2013-09-08 16:41:10.657 [NotebookApp] CRITICAL | Malformed message: ['stdout', '<IDS|MSG>', '0483c47b0ac7771daf8e4fcbb16a2bf17423c8184dadb4360d184dfac0fa7452', '{"msg_type":"stream","msg_id":"16c473bc-88d0-4d7f-9e15-37873a7de87a","username":"username","session":"5E965C55119F4E02A3FBA925AB9C921A"}', '{"session":"5E965C55119F4E02A3FBA925AB9C921A","msg_id":"D42CF3596E734F1FBE30D445E4C21C68","username":"username","msg_type":"execute_request"}', '{}', '{"data":"Progress:  95%  ETA: 0:00:01\\e[K","name":"stdout"}']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/base/zmqhandlers.py", line 68, in _on_zmq_reply
    msg = self._reserialize_reply(msg_list)
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/base/zmqhandlers.py", line 51, in _reserialize_reply
    msg = self.session.unserialize(msg_list)
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/session.py", line 808, in unserialize
    message['content'] = self.unpack(msg_list[4])
  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/session.py", line 83, in <lambda>
    json_unpacker = lambda s: extract_dates(jsonapi.loads(s))
  File "/usr/local/lib/python2.7/dist-packages/zmq/utils/jsonapi.py", line 81, in loads
    return jsonmod.loads(s, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 418, in raw_decode
    obj, end = self.scan_once(s, idx)
```
Not being a pythonista, I'm not certain of the right way to solve this problem.

**Comment by garrison** [comment]
Should this be closed now, with timholy/ProgressMeter.jl#7 marked as fixed?
