### ISSUE TITLE
Problem installing IJulia on Windows 10

### ISSUE THREAD

**Issue by pmarg** [JuliaLang/IJulia.jl#674]
Hi, 

I am trying to install IJulia on Windows 10 and I get the following error:
```julia
INFO: Building Conda
INFO: Building MbedTLS
Info: using prebuilt binaries
INFO: Building ZMQ
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
Solving environment: done

# All requested packages already installed.


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main_install.py", line 12, in execute
        delete_trash()
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 68, in delete_trash
        backoff_rmdir(path, max_tries=1)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 145, in backoff_rmdir
        _rmdir(join(root, dir))
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 134, in _rmdir
        exp_backoff_fn(rmtree, path, onerror=retry, max_tries=max_tries)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\__init__.py", line 30, in exp_backoff_fn
        result = fn(*args, **kwargs)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 212, in rmtree
        visit_files(root, files)
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 200, in visit_files
        rm(unlink, join(root, target))
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 196, in rm
        onerror(fn, childpath, sys.exc_info()[0])
      File "C:\Users\panag\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\gateways\disk\delete.py", line 126, in retry
        if getattr(exc_info[1], 'errno', None) == ENOENT:
    TypeError: 'type' object has no attribute '__getitem__'

`$ C:\Users\panag\.julia\v0.6\Conda\deps\usr\Scripts\conda install -y jupyter`

  environment variables:
                 CIO_TEST=<not set>
                  CONDARC=C:\Users\panag\.julia\v0.6\Conda\deps\usr\condarc-julia.yml
             CONDA_PREFIX=C:\Users\panag\.julia\v0.6\Conda\deps\usr
               CONDA_ROOT=C:\Users\panag\.julia\v0.6\Conda\deps\usr
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
                 HOMEPATH=\Users\panag
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\intel64_win_mic
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\panag\.julia\v0.6\Conda\deps\usr\Library\bin;C:\Users\panag\A
                          ppData\Local\Julia-0.6.3\bin;C:\Users\panag\AppData\Local\Julia-0.6.3\
                          bin;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.3
                          .210\windows\mpi\intel64\bin;C:\Program Files (x86)\Intel\iCLS
                          Client\;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_20
                          18.2.185\windows\mpi\intel64\bin;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files
                          (x86)\Common Files\Intel\Shared
                          Libraries\redist\intel64_win\compiler;C:\Program Files\Microsoft HPC
                          Pack 2012\Bin\;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.2\libnvvp;C:\Program Files\Intel\iCLS Client\;C:\Windo
                          ws\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wi
                          ndowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Strawberry\c\bin;
                          C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\WINDOWS\system32
                          ;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerS
                          hell\v1.0\;C:\Program Files (x86)\gdipp\;C:\Program Files
                          (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files
                          (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files
                          (x86)\Common Files\Seagate\SnapAPI\;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\syste
                          m32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPow
                          erShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Users\panag\AppData\Local\Microsoft\WindowsApps;C:\Users\panag\
                          AppData\Local\atom\bin;C:\Users\panag\AppData\Local\Programs\MiKTeX 2.
                          9\miktex\bin\x64\;C:\Users\panag\AppData\Local\Microsoft\WindowsApps;C
                          :\Users\panag\AppData\Local\Julia-0.6.3\bin\;C:\Program
                          Files\Microsoft VS Code\bin;.julia\v0.6\Conda\deps\usr\Scripts;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\panag\.julia\v0.6\Conda\deps\usr
       user config file : C:\Users\panag\.condarc
 populated config files : C:\Users\panag\.condarc
                          C:\Users\panag\.julia\v0.6\Conda\deps\usr\condarc-julia.yml
          conda version : 4.5.5
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : C:\Users\panag\.julia\v0.6\Conda\deps\usr  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\panag\.julia\v0.6\Conda\deps\usr\pkgs
                          C:\Users\panag\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\panag\.julia\v0.6\Conda\deps\usr\envs
                          C:\Users\panag\AppData\Local\conda\conda\envs
                          C:\Users\panag\.conda\envs
               platform : win-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/2.7.15 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
===================================================[ ERROR: IJulia ]====================================================
LoadError: failed process: Process(setenv(`'C:\Users\panag\.julia\v0.6\Conda\deps\usr\Scripts\conda.exe' install -y jupyter`,String["USERDOMAIN_ROAMINGPROFILE=DESKTOP-P7NBL0H", "JUPYTER=C:\\Users\\panag\\.julia\\v0.6\\Conda\\deps\\usr\\Scripts\\jupyter.exe", "HOMEPATH=\\Users\\panag", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "INSPECTOR_2018_DIR=C:\\Program Files (x86)\\IntelSWTools\\Inspector 2018\\", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "APPDATA=C:\\Users\\panag\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-P7NBL0H", "OS=Windows_NT", "PROCESSOR_REVISION=8e09", "TMP=C:\\Users\\panag\\AppData\\Local\\Temp", "MSMPI_LIB32=C:\\Program Files\\Microsoft HPC Pack 2012\\Lib\\i386\\", "IFORT_COMPILER18=C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018.3.210\\windows\\", "NVTOOLSEXT_PATH=C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\Users\\panag\\AppData\\Local\\Julia-0.6.3\\bin;C:\\Users\\panag\\AppData\\Local\\Julia-0.6.3\\bin;C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018.3.210\\windows\\mpi\\intel64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018.2.185\\windows\\mpi\\intel64\\bin;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\mpirt;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Program Files\\Microsoft HPC Pack 2012\\Bin\\;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\libnvvp;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Git\\cmd;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\gdipp\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Common Files\\Seagate\\SnapAPI\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\panag\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\panag\\AppData\\Local\\atom\\bin;C:\\Users\\panag\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Users\\panag\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\panag\\AppData\\Local\\Julia-0.6.3\\bin\\;C:\\Program Files\\Microsoft VS Code\\bin;.julia\\v0.6\\Conda\\deps\\usr\\Scripts;", "COMPUTERNAME=DESKTOP-P7NBL0H", "INTELGTDEBUGGERROOT=C:\\Program Files (x86)\\IntelSWTools\\debugger_2018\\gdb\\intel64_igfx\\", "CUDA_PATH_V9_2=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2", "VTUNE_AMPLIFIER_2018_DIR=C:\\Program Files (x86)\\IntelSWTools\\VTune Amplifier 2018\\", "USERNAME=panag", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Files\\Common Files", "ICPP_COMPILER18=C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018.3.210\\windows\\", "INTEL_LICENSE_FILE=C:\\Program Files (x86)\\Common Files\\\\Intel\\Licenses;C:\\Program Files (x86)\\Common Files\\Intel\\Licenses", "MSMPI_INC=C:\\Program Files\\Microsoft HPC Pack 2012\\Inc\\", "CUDA_PATH=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2", "USERPROFILE=C:\\Users\\panag", "CONDARC=C:\\Users\\panag\\.julia\\v0.6\\Conda\\deps\\usr\\condarc-julia.yml", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\panag\\.julia\\v0.6\\IJulia\\deps", "SystemDrive=C:", "HOMEDRIVE=C:", "TEMP=C:\\Users\\panag\\AppData\\Local\\Temp", "LOCALAPPDATA=C:\\Users\\panag\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "NUMBER_OF_PROCESSORS=4", "BuildLab=17134.rs4_release.180410-1804", "MSMPI_LIB64=C:\\Program Files\\Microsoft HPC Pack 2012\\Lib\\amd64\\", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\panag\\OneDrive", "ProgramFiles(x86)=C:\\Program Files (x86)", "I_MPI_ROOT=C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2018.3.210\\windows\\mpi", "INTEL_DEV_REDIST=C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\", "NVCUDASAMPLES9_2_ROOT=C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v9.2", "LOGONSERVER=\\\\DESKTOP-P7NBL0H", "CONDA_PREFIX=C:\\Users\\panag\\.julia\\v0.6\\Conda\\deps\\usr", "windir=C:\\WINDOWS", "BuildLabEx=17134.1.x86fre.rs4_release.180410-1804", "ADVISOR_2018_DIR=C:\\Program Files (x86)\\IntelSWTools\\Advisor 2018\\", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "NVCUDASAMPLES_ROOT=C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v9.2", "PROCESSOR_ARCHITECTURE=AMD64", "MIC_LD_LIBRARY_PATH=C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\intel64_win_mic", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading C:\Users\panag\.julia\v0.6\IJulia\deps\build.jl, in expression starting on line 117

========================================================================================================================
====================================================[ BUILD ERRORS ]====================================================
WARNING: IJulia had build errors.

 - packages with build errors remain installed in C:\Users\panag\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

===================================================================
```

I get the same error when I try:

```julia
using Conda
Conda.add("jupyter")
``` 
and 
```julia
Conda.update()
```

In cmd typing `where jupyter` returns the location of Conda.jl `C:\Users\.julia\v0.6\Conda\deps\usr\Scripts\jupyter.exe` and when I run Jupyter from the command line it opens properly.

I tried to use the Jupyter from the Anaconda distribution by finding the relevant paths with `jupyter --paths` and running for example:
```julia
ENV["JUPYTER"]="C:\\ProgramData\\Anaconda3\\share\\jupyter"
Pkg.build("IJulia")
```
I tried all the paths because I am not sure which one is the correct one, but none worked. 

Thank you for your help!

**Comment by stevengj** [comment]
This is a Conda problem, not an IJulia problem.  You might try deleting the `C:\Users\.julia\v0.6\Conda\deps\usr` directory and re-installing.
```jl
rm(raw"C:\Users\.julia\v0.6\Conda\deps\usr", recursive=true)
using Conda
Conda.add("jupyter")
```
