### ISSUE TITLE
Segfault when issuing plot command in IJulia notebook

### ISSUE THREAD

**Issue by marius311** [JuliaLang/IJulia.jl#686]
I'm trying to set up IJulia notebook on some cluster, and I'm getting a segfault any time I try to plot anything with PyPlot. This seems to be IJulia-related because if I use PyPlot from the Julia prompt, I'm not seeing the segfault (granted I should mention I don't see the plot as I've no GUI set up, but I do get the PyObject returned OK). I've enabled debugging options as described in the readme. I'm also using a debug build of Julia. The sequence of commands is simply `using PyPlot; plot([1,2,3])` and I see this output:

```
09:28:32(write task): EXECUTING plot([1,2,3])
09:28:33(write task): SENDING IPython Msg [ idents execute_input ] {
  parent_header = Dict{String,Any}(Pair{String,Any}("msg_id", "37882d278ee741d09748c9503f1a3313"),Pair{String,Any}("msg_type", "execute_request"),Pair{String,Any}("username", "username"),Pair{String,Any}("date", "2018-07-18T16:28:21.094546Z"),Pair{String,Any}("version", "5.2"),Pair{String,Any}("session", "38a5cd14aea049278a23e6ec36233a92")),
  header = Dict{String,Any}(Pair{String,Any}("msg_id", "d7a433ce-0a90-4ecc-9250-78634f24fe78"),Pair{String,Any}("msg_type", "execute_input"),Pair{String,Any}("username", "username"),Pair{String,Any}("date", 2018-07-18T09:28:32.963),Pair{String,Any}("version", "5.0"),Pair{String,Any}("session", "38a5cd14aea049278a23e6ec36233a92")),
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}(Pair{String,Any}("code", "plot([1,2,3])"),Pair{String,Any}("execution_count", 2))
}
signal (11): Segmentation fault
signal (11): Segmentation fault
while loading /global/u1/m/mariuswhile loading /global/u1/m/mariuswhile loading /global/u1/m/mariuswhile loading /global/u1/m/mariuswhile loading /global/u1/m/mariuswhile loading /global/u1/m/mariuswhile loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31

signal (11): Segmentation fault
.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31

signal (11): Segmentation fault
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31

signal (11): Segmentation fault
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31

signal (11): Segmentation fault
while loading /global/u1/m/marius/.julia/v0.6/IJulia/src/kernel.jl, in expression starting on line 31
[I 09:28:38.196 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```

Any ideas what's going on or how I can get more than this terse debug info? Many thanks for any suggestions! 

Version info (sorry for the overly long, not sure what all could be at play here):

<details>

```
julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
DEBUG build
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Pkg.status()
14 required packages:
 - BenchmarkTools                0.3.2
 - ClusterManagers               0.1.2              4d7d8058 (dirty)
 - Dierckx                       0.3.0
 - Glob                          1.1.1
 - IJulia                        1.8.0              004e0fbd (dirty) # the dirty here are just the debug changes from the readme
 - Images                        0.13.0
 - JLD2                          0.0.6
 - Lazy                          0.12.1
 - MPI                           0.6.0+             master
 - NPZ                           0.2.0
 - ProgressMeter                 0.5.6
 - PyPlot                        2.6.0
 - Revise                        0.1.1
 - Roots                         0.6.0
96 additional packages:
 - AbstractFFTs                  0.3.2
 - AxisAlgorithms                0.2.0
 - AxisArrays                    0.2.1
 - BinDeps                       0.8.8
 - BinaryProvider                0.3.3
 - Blosc                         0.5.0
 - CMBLensing                    0.0.0-             master (unregistered)
 - CMakeWrapper                  0.1.0
 - Calculus                      0.4.0
 - CatIndices                    0.1.0
 - CodecZlib                     0.4.3
 - ColorTypes                    0.6.7
 - ColorVectorSpace              0.5.2
 - Colors                        0.8.2
 - Combinatorics                 0.6.0
 - CommonSubexpressions          0.1.0
 - Compat                        0.70.0
 - ComputationalResources        0.2.0
 - Conda                         0.8.1
 - CoordinateTransformations     0.4.1
 - CustomUnitRanges              0.1.0
 - DataStructures                0.8.3
 - DiffEqBase                    3.13.0
 - DiffEqDiffTools               0.4.1
 - DiffResults                   0.0.3
 - DiffRules                     0.0.6
 - Distances                     0.6.0
 - DualNumbers                   0.4.0
 - FFTViews                      0.1.0
 - FFTW                          0.0.4
 - FileIO                        0.9.1
 - FixedPointNumbers             0.4.6
 - ForwardDiff                   0.7.5
 - FunctionWrappers              0.1.0
 - Graphics                      0.3.0
 - HDF5                          0.9.3
 - IdentityRanges                0.1.0
 - ImageAxes                     0.4.0
 - ImageCore                     0.7.0-             master
 - ImageDistances                0.0.2
 - ImageFiltering                0.3.0
 - ImageMetadata                 0.4.1
 - ImageMorphology               0.0.2
 - ImageTransformations          0.4.1
 - IndirectArrays                0.4.2
 - Interpolations                0.7.3
 - IntervalSets                  0.2.0
 - IterTools                     0.2.1
 - IteratorInterfaceExtensions   0.0.2
 - JLD                           0.8.3
 - JSON                          0.17.2
 - LaTeXStrings                  1.0.0
 - LegacyStrings                 0.3.0
 - LineSearches                  6.0.2
 - LinearMaps                    1.0.4
 - MacroTools                    0.4.2
 - MappedArrays                  0.0.7
 - MbedTLS                       0.5.12
 - Missings                      0.2.10
 - NLSolversBase                 6.1.1
 - NaNMath                       0.3.1
 - NamedTuples                   4.0.2
 - Nullables                     0.0.6
 - ODE                           2.0.0-             master
 - OffsetArrays                  0.6.0
 - Optim                         0.15.2
 - PaddedViews                   0.3.0
 - Parameters                    0.9.0
 - Polynomials                   0.3.2
 - PositiveFactorizations        0.1.0
 - PyCall                        1.17.1
 - RangeArrays                   0.2.0
 - Ratios                        0.2.0
 - RecipesBase                   0.3.1
 - RecursiveArrayTools           0.15.0
 - Reexport                      0.1.0
 - Requires                      0.4.4
 - Rotations                     0.7.1
 - SHA                           0.5.7
 - SIUnits                       0.1.0
 - SPTLensing                    0.0.0-             master (unregistered, dirty)
 - ShowItLikeYouBuildIt          0.2.0
 - SimpleTraits                  0.6.0
 - SortingAlgorithms             0.2.1
 - SpecialFunctions              0.6.0
 - StaticArrays                  0.7.2
 - StatsBase                     0.23.1
 - TableTraits                   0.2.0
 - TexExtensions                 0.1.0
 - TiledIteration                0.1.0
 - TranscodingStreams            0.5.2
 - URIParser                     0.3.1
 - VersionParsing                1.1.1
 - WoodburyMatrices              0.3.0
 - ZMQ                           0.6.2
 - ZipFile                       0.5.0

# packages in environment at /global/homes/m/marius/.conda/envs/local:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3            py37h28b3542_0  
asn1crypto                0.24.0                   py37_0  
attrs                     18.1.0                   py37_0  
automat                   0.7.0                    py37_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    2.1.3                    py37_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py37_0  
cffi                      1.11.5           py37h9745a5d_0  
constantly                15.1.0           py37h28b3542_0  
cryptography              2.2.2            py37h14c3975_0  
cycler                    0.10.0                   py37_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py37_0  
entrypoints               0.2.3                    py37_2  
expat                     2.2.5                he0dffb1_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_0  
glib                      2.56.1               h000015b_0  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
html5lib                  1.0.1                    py37_0  
hyperlink                 18.0.0                   py37_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py37_0  
incremental               17.5.0                   py37_0  
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py37_0  
ipython                   6.4.0                    py37_1  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.2.1                    py37_0  
jedi                      0.12.0                   py37_1  
jinja2                    2.10                     py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_5  
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.3                    py37_0  
jupyter_console           5.2.0                    py37_1  
jupyter_core              4.4.0                    py37_0  
kiwisolver                1.0.1            py37hf484d3e_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              7.2.0                hdf63c60_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
lxml                      4.2.3                     <pip>
markupsafe                1.0              py37h14c3975_1  
matplotlib                2.2.2            py37hb69df0a_2  
mistune                   0.8.3            py37h14c3975_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2            py37h651fb7a_0  
mkl_random                1.0.1            py37h4414c95_1  
nbconvert                 5.3.1                    py37_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  hf484d3e_0  
notebook                  5.5.0                    py37_0  
numpy                     1.14.5           py37h1b885b7_4  
numpy-base                1.14.5           py37hdbf6ddf_4  
openssl                   1.0.2o               h20670df_0  
pandoc                    2.2.1                h629c226_0  
pandocfilters             1.4.2                    py37_1  
parso                     0.2.1                    py37_0  
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.4                    py37_0  
pip                       10.0.1                   py37_0  
prometheus_client         0.2.0                    py37_0  
prompt_toolkit            1.0.15                   py37_0  
ptyprocess                0.6.0                    py37_0  
pyasn1                    0.4.3                    py37_0  
pyasn1-modules            0.2.2                    py37_0  
pycparser                 2.18                     py37_1  
pygments                  2.2.0                    py37_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.2.0                    py37_1  
pyqt                      5.9.2            py37h22d08a2_0  
python                    3.7.0                hc3d631a_0  
python-dateutil           2.7.3                    py37_0  
pytz                      2018.5                   py37_0  
PyYAML                    3.13                      <pip>
pyzmq                     17.0.0           py37h14c3975_3  
qt                        5.9.6                h52aff34_0  
qtconsole                 4.3.1                    py37_0  
readline                  7.0                  ha6073c6_4  
scipy                     1.1.0            py37hc49cb51_0  
send2trash                1.5.0                    py37_0  
service_identity          17.0.0           py37h28b3542_0  
setuptools                39.2.0                   py37_0  
simplegeneric             0.8.1                    py37_2  
sip                       4.19.8           py37hf484d3e_0  
six                       1.11.0                   py37_1  
sqlite                    3.24.0               h84994c4_0  
terminado                 0.8.1                    py37_1  
testpath                  0.3.1                    py37_0  
tk                        8.6.7                hc745277_3  
tornado                   5.0.2            py37h14c3975_0  
traitlets                 4.3.2                    py37_0  
twisted                   18.4.0           py37h14c3975_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.31.1                   py37_0  
widgetsnbextension        3.2.1                    py37_0  
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5                hf484d3e_0  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py37_0  
zope.interface            4.5.0            py37h14c3975_0  

```

**Comment by marius311** [comment]
I should also mention that plotting from an IPython kernel on the same system using the same Python executable that Julia uses *does* work fine.

**Comment by marius311** [comment]
I managed to reproduce this from Julia prompt too and grab a backtrace with gdb, which looks like 
```
Thread 34 "julia-debug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aab5c801680 (LWP 46701)]
0x00002aaabeb3ca7e in mkl_blas_avx2_xdcopy () from /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_avx2.so
Missing separate debuginfos, use: zypper install Mesa-libGL1-debuginfo-17.0.5-117.5.1.x86_64 Mesa-libglapi0-debuginfo-17.0.5-117.5.1.x86_64 libX11-6-debuginfo-1.6.2-11.1.x86_64 libX11-xcb1-debuginfo-1.6.2-11.1.x86_64 libXau6-debuginfo-1.0.8-4.58.x86_64 libXcursor1-debuginfo-1.1.14-4.3.1.x86_64 libXdamage1-debuginfo-1.1.4-7.54.x86_64 libXext6-debuginfo-1.3.2-4.3.1.x86_64 libXfixes3-debuginfo-5.0.1-7.1.x86_64 libXi6-debuginfo-1.7.4-17.1.x86_64 libXrender1-debuginfo-0.9.8-7.1.x86_64 libXxf86vm1-debuginfo-1.1.3-3.54.x86_64 libdrm2-debuginfo-2.4.76-1.14.x86_64 libgcc_s1-debuginfo-7.2.1+r253435-2.4.x86_64 libnuma1-debuginfo-2.0.9-9.1.x86_64 libxshmfence1-debuginfo-1.1-1.28.x86_64 sssd-debuginfo-1.13.4-34.7.1.x86_64
(gdb) bt
#0  0x00002aaabeb3ca7e in mkl_blas_avx2_xdcopy () from /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_avx2.so
#1  0x00002aaabb9a4225 in mkl_blas_dcopy () from /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_intel_thread.so
#2  0x00002aaabb485563 in __kmp_invoke_microtask ()
   from /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/../../../compiler/lib/intel64/libiomp5.so
#3  0x00002aaabb44d3ea in __kmp_invoke_task_func (gtid=1135623600) at ../../src/kmp_runtime.cpp:7277
#4  0x00002aaabb44caab in __kmp_launch_thread (this_thr=0x7607b21743b03db0) at ../../src/kmp_runtime.cpp:5885
#5  0x00002aaabb4859c0 in _INTERNAL_26_______src_z_Linux_util_cpp_d7ee2e5e::__kmp_launch_worker (thr=0x7607b21743b03db0) at ../../src/z_Linux_util.cpp:585
#6  0x00002aaaab910724 in start_thread () from /lib64/libpthread.so.0
#7  0x00002aaaabc0ec1d in clone () from /lib64/libc.so.6
```

Which means its likely this https://github.com/JuliaPy/PyPlot.jl/issues/100 which I had run into before but thought was solved here. In any case, its unrelated to IJulia, sorry for the noise!
