### ISSUE TITLE
`notebook()` fails in new installation of IJulia in Julia 0.7 on Ubuntu 16.04

### ISSUE THREAD

**Issue by Sleort** [JuliaLang/IJulia.jl#744]
I have just installed IJulia under Conda in Julia 0.7, but...
```
(v0.7) pkg> add IJulia
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [7073ff75] + IJulia v1.11.1
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [7073ff75] + IJulia v1.11.1
  [739be429] + MbedTLS v0.6.0
  [b85f4697] + SoftGlobalScope v1.0.4
  [c2297ded] + ZMQ v1.0.0

(v0.7) pkg> build IJulia
  Building Conda ──→ `~/.julia/packages/Conda/m7vem/deps/build.log`
  Building ZMQ ────→ `~/.julia/packages/ZMQ/ABGOx/deps/build.log`
  Building MbedTLS → `~/.julia/packages/MbedTLS/Qo8TN/deps/build.log`
  Building IJulia ─→ `~/.julia/packages/IJulia/k5o7j/deps/build.log`

julia> using IJulia
[ Info: Recompiling stale cache file /home/troels/.julia/compiled/v0.7/IJulia/nfu7T.ji for IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]

julia> notebook()
Process(setenv(`/home/troels/.julia/packages/Conda/m7vem/deps/usr/bin/jupyter notebook --NotebookApp.iopub_data_rate_limit=2147483647`; dir="/home/troels"), ProcessExited(1))
```
...and nothing else happens, i.e. the notebook does not open. For what it is worth, IJulia worked flawlessly under Julia 0.6.4 on the same machine.

Is this a bug or something I've messed up?

**Comment by stevengj** [comment]
Does running `/home/troels/.julia/packages/Conda/m7vem/deps/usr/bin/jupyter notebook` manually in the terminal work?

**Comment by Sleort** [comment]
No, unfortunately not:
```
troels@troels-700Z7C:~$ /home/troels/.julia/packages/Conda/m7vem/deps/usr/bin/jupyter notebook
[I 08:51:15.143 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 08:51:15.663 NotebookApp] Serving notebooks from local directory: /home/troels
[I 08:51:15.663 NotebookApp] The Jupyter Notebook is running at:
[I 08:51:15.663 NotebookApp] http://localhost:8888/?token=cad702ce02da537a672d7e102f618a6aebc1c1f2e6f64f84
[I 08:51:15.663 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/webbrowser.py", line 58, in get
    command = _browsers[browser.lower()]
KeyError: '/usr/bin/google-chrome'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/site-packages/notebook/notebookapp.py", line 1697, in start
    browser = webbrowser.get(self.browser or None)
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/webbrowser.py", line 60, in get
    command = _synthesize(browser)
  File "/home/troels/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by stevengj** [comment]
Since the error occurs when you run `jupyter notebook` manually, it is unrelated to IJulia and should be filed with the Jupyter project if it is still occurring.
