### ISSUE TITLE
kernel not connect julia 1.0.1

### ISSUE THREAD

**Issue by yolanda123a** [JuliaLang/IJulia.jl#753]
i installed julia 1.0.1
and in notebook said kernel error not connect

and this is description
```
Traceback (most recent call last):
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\varie\.julia\packages\Conda\m7vem\deps\usr\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```

**Comment by stevengj** [comment]
If you run `build IJulia` at the pkg prompt does it succeed?

**Comment by mindon** [comment]
Facing same kind of issue with successful pkg>`add IJulia` and pkg>`build IJulia` and >`using IJulia` under julia console.

The websocket connection to julia-1.1.0 kernel always timeout in browser...

I had set ENV["IJULIA_DEBUG"]=true before `build IJulia`
how can i find logs to trace the issue? thanks

**Comment by stevengj** [comment]
A `FileNotFoundError` usually means that you moved your Julia installation and need to re-run `build IJulia` …

@mindon, it sounds like your issue is different.  Does the Python kernel work for you?

**Comment by mindon** [comment]
> @mindon, it sounds like your issue is different, since you are reporting a timeout. Does the Python kernel work for you?

Python kernel and another R kernel are both working well

**Comment by stevengj** [comment]
Sounds resolved?
