### ISSUE TITLE
Kernel dead and fail rebuild IJulia

### ISSUE THREAD

**Issue by sf-nevermore** [JuliaLang/IJulia.jl#772]
Hi,

I tried @everywhere include("somepackage.jl") on notebook, the kernel die and I can no longer start IJulia notebook. So I try to rebuild it. Then I keep getting the following issue. How should I fix it?

Thanks.
![image](https://user-images.githubusercontent.com/7236497/47868734-3d801c00-ddc2-11e8-9d7c-a4bce2316dac.png)

**Comment by stevengj** [comment]
Looks like your Anaconda installation is broken somehow?  For example, does
```sh
jupyter kernelspec list
```
work?

Have you considered letting Julia maintain its own Conda installation?  This might be easier than managing your own.

**Comment by leejm516** [comment]
Similar issue in my Win10. I am not sure whether this issue is related to Julia 1.0.2, although I got this error after updating julia.
In case of me, jupyter works very well as @stevengj suggested.

```
julia> Pkg.build("IJulia")
  Building Conda ──→ `C:\Users\kiost-ljm\.julia\packages\Conda\uQitS\deps\build.log`
  Building ZMQ ────→ `C:\Users\kiost-ljm\.julia\packages\ZMQ\ABGOx\deps\build.log`
  Building MbedTLS → `C:\Users\kiost-ljm\.julia\packages\MbedTLS\r1Ufc\deps\build.log`
  Building IJulia ─→ `C:\Users\kiost-ljm\.julia\packages\IJulia\DL02A\deps\build.log`
┌ Error: Error building `IJulia`:
│ Solving environment: ...working... done
│
│ # All requested packages already installed.
│
│ Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
│ Traceback (most recent call last):
│   File "D:\Apps\Anaconda3\envs\python_jl\Scripts\jupyter-kernelspec-script.py", line 6, in <module>
│     from jupyter_client.kernelspecapp import KernelSpecApp
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
│     from .connect import *
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
│     import zmq
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\__init__.py", line 47, in <module>
│     from zmq import backend
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
│     reraise(*exc_info)
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
│     raise value
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
│     _ns = select_backend(first)
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
│     mod = __import__(name, fromlist=public_api)
│   File "D:\Apps\Anaconda3\envs\python_jl\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
│     from . import (constants, error, message, context,
│ ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
│ [ Info: Installing Jupyter via the Conda package.
│ [ Info: Running `conda install -y jupyter` in root environment
│ [ Info: Found Jupyter version 4.4.0: D:\Apps\Anaconda3\envs\python_jl\Scripts\jupyter
│ [ Info: Installing Julia kernelspec julia-1.0
│ ERROR: LoadError: failed process: Process(`'D:\Apps\Anaconda3\envs\python_jl\python.exe' 'D:\Apps\Anaconda3\envs\python_jl\Scripts\jupyter-kernelspec-script.py' install --replace --user 'C:\Users\KIOST-~1\AppData\Local\Temp\julia-1.0'`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:705 [inlined]
│  [3] #run#504(::Bool, ::Function, ::Cmd) at .\process.jl:663
│  [4] run at .\process.jl:661 [inlined]
│  [5] #installkernel#4(::String, ::Function, ::String) at C:\Users\kiost-ljm\.julia\packages\IJulia\DL02A\deps\kspec.jl:85
│  [6] installkernel(::String) at C:\Users\kiost-ljm\.julia\packages\IJulia\DL02A\deps\kspec.jl:36
│  [7] top-level scope at logging.jl:308
│  [8] top-level scope at logging.jl:307
│  [9] top-level scope at C:\Users\kiost-ljm\.julia\packages\IJulia\DL02A\deps\build.jl:41
│  [10] include at .\boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1044
│  [12] include(::Module, ::String) at .\sysimg.jl:29
│  [13] include(::String) at .\client.jl:392
│  [14] top-level scope at none:0
│ in expression starting at C:\Users\kiost-ljm\.julia\packages\IJulia\DL02A\deps\build.jl:9
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

```

**Comment by stevengj** [comment]
We no longer use `jupyter` during build, so hopefully this issue is moot.
