### ISSUE TITLE
Add IJulia Error

### ISSUE THREAD

**Issue by MtMao** [JuliaLang/IJulia.jl#790]
I have Python 3.7.0 installed in Anaconda, and I have Julia 1.0.3 installed.

Then I tried to add IJulia, however, there seems to be something wrong with module `jupyter-kernelspec`.

I was aware of the issue [#778](https://github.com/JuliaLang/IJulia.jl/issues/778), and I think this is a different problem.

Any help is appreciated!
```
julia> ENV["JUPYTER"]="D:\\Software\\Anaconda3\\Scripts\\jupyter"
"D:\\Software\\Anaconda3\\Scripts\\jupyter"
```

```
julia> using Pkg
```

```
julia> Pkg.add("IJulia")
   Cloning default registries into C:\Users\Mao\.julia\registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
 Resolving package versions...
 Installed SoftGlobalScope ─ v1.0.8
 Installed VersionParsing ── v1.1.3
 Installed Compat ────────── v1.4.0
 Installed BinaryProvider ── v0.5.3
 Installed ZMQ ───────────── v1.0.0
 Installed Conda ─────────── v1.1.1
 Installed MbedTLS ───────── v0.6.6
 Installed IJulia ────────── v1.14.1
 Installed JSON ──────────── v0.20.0
  Updating `C:\Users\Mao\.julia\environments\v1.0\Project.toml`
  [7073ff75] + IJulia v1.14.1
  Updating `C:\Users\Mao\.julia\environments\v1.0\Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.3
  [34da2185] + Compat v1.4.0
  [8f4d0f93] + Conda v1.1.1
  [7073ff75] + IJulia v1.14.1
  [682c06a0] + JSON v0.20.0
  [739be429] + MbedTLS v0.6.6
  [b85f4697] + SoftGlobalScope v1.0.8
  [81def892] + VersionParsing v1.1.3
  [c2297ded] + ZMQ v1.0.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  Building Conda ──→ `C:\Users\Mao\.julia\packages\Conda\uQitS\deps\build.log`
  Building ZMQ ────→ `C:\Users\Mao\.julia\packages\ZMQ\ABGOx\deps\build.log`
  Building MbedTLS → `C:\Users\Mao\.julia\packages\MbedTLS\r1Ufc\deps\build.log`
  Building IJulia ─→ `C:\Users\Mao\.julia\packages\IJulia\DL02A\deps\build.log`
┌ Error: Error building `IJulia`:
│ Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
│ Traceback (most recent call last):
│   File "D:\Software\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 6, in <module>
│     from jupyter_client.kernelspecapp import KernelSpecApp
│   File "D:\Software\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
│     from .connect import *
│   File "D:\Software\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
│     import zmq
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
│     from zmq import backend
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
│     reraise(*exc_info)
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
│     raise value
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
│     _ns = select_backend(first)
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
│     mod = __import__(name, fromlist=public_api)
│   File "D:\Software\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
│     from . import (constants, error, message, context,
│ ImportError: DLL load failed: The specified module could not be found.
│ [ Info: Found Jupyter version 4.4.0: D:\Software\Anaconda3\Scripts\jupyter
│ [ Info: Installing Julia kernelspec julia-1.0
│ ERROR: LoadError: failed process: Process(`'D:\Software\Anaconda3\Scripts\jupyter-kernelspec.exe' install --replace --user 'C:\Users\Mao\AppData\Local\Temp\julia-1.0'`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:705 [inlined]
│  [3] #run#503(::Bool, ::Function, ::Cmd) at .\process.jl:663
│  [4] run at .\process.jl:661 [inlined]
│  [5] #installkernel#4(::String, ::Function, ::String) at C:\Users\Mao\.julia\packages\IJulia\DL02A\deps\kspec.jl:106
│  [6] installkernel(::String) at C:\Users\Mao\.julia\packages\IJulia\DL02A\deps\kspec.jl:36
│  [7] top-level scope at C:\Users\Mao\.julia\packages\IJulia\DL02A\deps\build.jl:92
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1044
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:392
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\Mao\.julia\packages\IJulia\DL02A\deps\build.jl:9
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097
```

**Comment by stevengj** [comment]
Looks like you are using your own Anaconda installation, and it is broken.

(Does `jupyter kernelspec list` work if you run it manually?)

**Comment by MtMao** [comment]
@stevengj it works.
```
(base) C:\WINDOWS\system32>jupyter kernelspec list
Available kernels:
  python2    D:\Software\Anaconda3\share\jupyter\kernels\python2
  python3    D:\Software\Anaconda3\share\jupyter\kernels\python3
```

**Comment by stevengj** [comment]
IJulia no longer uses the `kernelspec` command, so this issue should be moot now.
