### ISSUE TITLE
Failed to start kernel

### ISSUE THREAD

**Issue by TheSodesa** [JuliaLang/IJulia.jl#824]
Trying to open up a notebook after starting Jupyter up with `IJulia.notebook()` on Julia 1.1 nets me the following error message:
```
    Traceback (most recent call last):
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "/Users/soderhos/.julia/conda/3/lib/python3.7/subprocess.py", line 1516, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia': '/Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia'
```
It seems like Jupyter is trying to locate Julia 1.0, even though the notebook session was started with Julia 1.1. Why would this happen?

**Comment by stevengj** [comment]
When you installed the new version of Julia and deleted the old one, you have to launch the Julia command line and run `build IJulia` at the package prompt (to tell Jupyter where to find Julia).

See https://github.com/JuliaLang/IJulia.jl#updating-julia-and-ijulia
