### ISSUE TITLE
Error in utf-8 decoding

### ISSUE THREAD

**Issue by olynch** [JuliaLang/IJulia.jl#927]
When I run

```julia
using HTTP
HTTP.request("GET", "http://www.pngonly.com/wp-content/uploads/2017/06/Rabbit-Free-PNG-Image.png")
```

in a jupyter notebook, I get the error

```
[E 09:03:12.097 LabApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
        callback(*args, **kwargs)
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 412, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/jupyter_client/session.py", line 943, in deserialize
        message['content'] = self.unpack(msg_list[4])
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/jupyter_client/session.py", line 91, in <lambda>
        json_unpacker = lambda s: jsonapi.loads(s)
      File "/nix/store/4fvh5q30g5wm0ds8yjing53a0p31p20f-python3-3.8.2-env/lib/python3.8/site-packages/zmq/utils/jsonapi.py", line 54, in loads
        s = s.decode('utf8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 308: invalid start byte
```

I am working in a docker container produced by jupyter-repo2docker.

**Comment by stevengj** [comment]
It seems like this is a bug in HTTP: it [writes part of the message body](https://github.com/JuliaWeb/HTTP.jl/blob/1f04e0e00a4bb8d36fd0112d86ebf9356575abce/src/Messages.jl#L540-L541) to the output even if that output is arbitrary binary data rather than valid UTF-8.

The simplest workaround is to not print the request, just append a semicolon.  e.g. this works:
```jl
r = HTTP.request("GET", "http://www.pngonly.com/wp-content/uploads/2017/06/Rabbit-Free-PNG-Image.png");
display("image/png", r.body)
```

Probably don't print the request result as a string, since image/png data is not valid as a string.

**Comment by stevengj** [comment]
But IJulia should probably also be more cautious here in displaying binary data as "text/plain".
